export interface SinhVien {
  maSinhVien: String;
  CMND: String;
  ho: String;
  ten:String;
  gioiTinh: Number;
  ngaySinh: String;
  diaChiThuongTru: String;
  diaChiTamTru: String;
  sdt: String;
  email: String;
  matKhau: String;
  tokens: String;
  hoTenCha: String;
  hoTenMe: String;
  sdtCha: String;
  sdtMe: String;
  maLopHoc: String;
  trangThai: String;
  nguoiTao: String;
  nguoiChinhSua: String;
}
// maSinhVien
// CMND
// ho
// ten
// gioiTinh
// ngaySinh
// diaChiThuongTru
// diaChiTamTru
// sdt
// email
// matKhau
// tokens
// hoTenCha
// hoTenMe
// sdtCha
// sdtMe
// maLopHoc
// trangThai
// nguoiTao
// nguoiChinhSua
